# Generated by Django 5.2.12 on 2026-03-25 17:07

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("artifacts", "0001_initial"),
        ("cases", "0001_initial"),
        ("extraction", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsumerDutyOutcome",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("products_services", "Products and services"),
                            ("price_value", "Price and value"),
                            ("consumer_understanding", "Consumer understanding"),
                            ("consumer_support", "Consumer support"),
                        ],
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField()),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="EvidenceLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("supporting", "Supporting"),
                            ("contradicting", "Contradicting"),
                            ("contextual", "Contextual"),
                            ("missing_expected_source", "Missing expected source"),
                        ],
                        max_length=32,
                    ),
                ),
                ("rationale", models.TextField()),
                (
                    "score",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_links",
                        to="cases.reviewcase",
                    ),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_links",
                        to="extraction.claim",
                    ),
                ),
                (
                    "outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_links",
                        to="obligations.consumerdutyoutcome",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evidence_links",
                        to="artifacts.documentsection",
                    ),
                ),
            ],
        ),
    ]
