# Generated by Django 5.2.12 on 2026-03-25 17:07

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewCase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("reference_code", models.CharField(max_length=64, unique=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("ingestion_pending", "Ingestion pending"),
                            ("parsing", "Parsing"),
                            ("parsed", "Parsed"),
                            ("extraction_pending", "Extraction pending"),
                            ("extracted", "Extracted"),
                            ("mapping_pending", "Mapping pending"),
                            ("mapped", "Mapped"),
                            ("assessment_pending", "Assessment pending"),
                            ("assessed", "Assessed"),
                            ("needs_review", "Needs review"),
                            ("approved", "Approved"),
                            ("escalated", "Escalated"),
                            ("archived", "Archived"),
                            ("failed", "Failed"),
                        ],
                        default="new",
                        max_length=32,
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("unassigned", "Unassigned"),
                            ("assigned", "Assigned"),
                            ("in_review", "In review"),
                            ("overridden", "Overridden"),
                            ("approved", "Approved"),
                            ("escalated", "Escalated"),
                            ("closed", "Closed"),
                        ],
                        default="unassigned",
                        max_length=32,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=16,
                    ),
                ),
                (
                    "case_type",
                    models.CharField(
                        choices=[
                            ("complaint_review", "Complaint review"),
                            ("support_review", "Support review"),
                            ("disclosure_review", "Disclosure review"),
                        ],
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("correlation_id", models.CharField(db_index=True, max_length=64)),
                ("latest_eval_run_id", models.UUIDField(blank=True, null=True)),
                ("degraded_mode_active", models.BooleanField(default=False)),
                ("dedupe_key", models.CharField(blank=True, max_length=255, null=True)),
                ("summary_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "assigned_reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "priority", "created_at"],
                        name="cases_revie_status_42f906_idx",
                    )
                ],
            },
        ),
    ]
