# Generated by Django 5.2.12 on 2026-03-25 17:30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("version_label", models.CharField(max_length=64)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("extraction", "Extraction"),
                            ("mapping", "Mapping"),
                            ("assessment", "Assessment"),
                            ("recommendation", "Recommendation"),
                        ],
                        max_length=32,
                    ),
                ),
                ("template_text", models.TextField()),
                ("schema_version", models.CharField(max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "recommended_action",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("review", "Review"),
                            ("escalate", "Escalate"),
                            ("request_more_evidence", "Request more evidence"),
                        ],
                        max_length=32,
                    ),
                ),
                ("recommended_priority", models.CharField(max_length=16)),
                ("executive_summary", models.TextField()),
                ("structured_rationale", models.JSONField(blank=True, default=dict)),
                ("confidence", models.FloatField()),
                ("citation_count", models.IntegerField(default=0)),
                ("model_version", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation",
                        to="cases.reviewcase",
                    ),
                ),
                (
                    "prompt_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendations",
                        to="recommendations.promptversion",
                    ),
                ),
            ],
        ),
    ]
