FROM python:3.14-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY backend/requirements /app/backend/requirements
RUN pip install --upgrade pip && pip install -r /app/backend/requirements/dev.txt

COPY . /app
