# Generated by Django 5.2.12 on 2026-03-25 17:07

import uuid

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "artifact_type",
                    models.CharField(
                        choices=[
                            ("complaint", "Complaint"),
                            ("support_transcript", "Support transcript"),
                            ("disclosure", "Disclosure"),
                            ("policy_excerpt", "Policy excerpt"),
                            ("script", "Script"),
                            ("internal_note", "Internal note"),
                        ],
                        max_length=32,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=128)),
                (
                    "source_channel",
                    models.CharField(
                        choices=[
                            ("upload", "Upload"),
                            ("seeded_demo", "Seeded demo"),
                            ("api", "API"),
                            ("manual_entry", "Manual entry"),
                        ],
                        max_length=32,
                    ),
                ),
                ("storage_path", models.CharField(max_length=500)),
                ("sha256_checksum", models.CharField(max_length=64)),
                (
                    "parse_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("parsed", "Parsed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("parse_error_code", models.CharField(blank=True, max_length=64, null=True)),
                ("text_length", models.IntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="cases.reviewcase",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("section_index", models.IntegerField()),
                ("heading", models.CharField(blank=True, max_length=255, null=True)),
                ("text", models.TextField()),
                ("char_start", models.IntegerField()),
                ("char_end", models.IntegerField()),
                ("page_number", models.IntegerField(blank=True, null=True)),
                ("parser_confidence", models.FloatField(blank=True, null=True)),
                (
                    "embedding_vector",
                    pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
                ),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="artifacts.sourceartifact",
                    ),
                ),
            ],
            options={
                "ordering": ["artifact", "section_index"],
            },
        ),
        migrations.AddIndex(
            model_name="sourceartifact",
            index=models.Index(
                fields=["case", "artifact_type"], name="artifacts_s_case_id_39af85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sourceartifact",
            index=models.Index(
                fields=["case", "sha256_checksum"], name="artifacts_s_case_id_8d0e1a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceartifact",
            constraint=models.UniqueConstraint(
                fields=("case", "sha256_checksum"), name="uq_case_checksum"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentsection",
            constraint=models.UniqueConstraint(
                fields=("artifact", "section_index"), name="uq_artifact_section_index"
            ),
        ),
    ]
