# Generated by Django 5.2.12 on 2026-03-25 17:30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelExecutionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("task_name", models.CharField(max_length=64)),
                ("provider_name", models.CharField(max_length=64)),
                ("model_name", models.CharField(max_length=128)),
                ("latency_ms", models.IntegerField()),
                ("input_token_estimate", models.IntegerField(default=0)),
                ("output_token_estimate", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("timeout", "Timeout"),
                            ("schema_fail", "Schema fail"),
                            ("provider_error", "Provider error"),
                            ("fallback_used", "Fallback used"),
                        ],
                        max_length=32,
                    ),
                ),
                ("cost_estimate", models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_execution_logs",
                        to="cases.reviewcase",
                    ),
                ),
            ],
        ),
    ]
