# Generated by Django 5.2.12 on 2026-03-25 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("observability", "0001_initial"),
        ("recommendations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelexecutionlog",
            name="prompt_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="execution_logs",
                to="recommendations.promptversion",
            ),
        ),
        migrations.AddIndex(
            model_name="modelexecutionlog",
            index=models.Index(
                fields=["case", "task_name", "created_at"], name="observabili_case_id_530dc0_idx"
            ),
        ),
    ]
