# Generated by Django 5.2.12 on 2026-03-25 17:30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("artifacts", "0001_initial"),
        ("cases", "0001_initial"),
        ("extraction", "0001_initial"),
        ("obligations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContradictionFlag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "contradiction_type",
                    models.CharField(
                        choices=[
                            ("date_conflict", "Date conflict"),
                            ("policy_conflict", "Policy conflict"),
                            ("statement_conflict", "Statement conflict"),
                            ("support_gap", "Support gap"),
                        ],
                        max_length=32,
                    ),
                ),
                ("severity", models.CharField(max_length=16)),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contradiction_flags",
                        to="cases.reviewcase",
                    ),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contradiction_flags",
                        to="extraction.claim",
                    ),
                ),
                (
                    "primary_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primary_contradictions",
                        to="artifacts.documentsection",
                    ),
                ),
                (
                    "secondary_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secondary_contradictions",
                        to="artifacts.documentsection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupportAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("supported", "Supported"),
                            ("weak_support", "Weak support"),
                            ("missing_support", "Missing support"),
                            ("contradictory_support", "Contradictory support"),
                            ("stale_support", "Stale support"),
                        ],
                        max_length=32,
                    ),
                ),
                ("confidence", models.FloatField()),
                ("requires_review", models.BooleanField(default=False)),
                ("assessment_reason", models.TextField()),
                ("rules_triggered", models.JSONField(blank=True, default=list)),
                ("model_version", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="cases.reviewcase",
                    ),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="extraction.claim",
                    ),
                ),
                (
                    "outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="obligations.consumerdutyoutcome",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["case", "status", "requires_review"],
                        name="assessments_case_id_eb2ec4_idx",
                    )
                ],
            },
        ),
    ]
