# Generated by Django 5.2.12 on 2026-03-25 17:07

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("artifacts", "0001_initial"),
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "claim_type",
                    models.CharField(
                        choices=[
                            ("customer_harm", "Customer harm"),
                            ("misleading_explanation", "Misleading explanation"),
                            ("support_delay", "Support delay"),
                            ("unclear_fee", "Unclear fee"),
                            ("inadequate_disclosure", "Inadequate disclosure"),
                            ("poor_outcome_indicator", "Poor outcome indicator"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("claim_text", models.TextField()),
                ("normalized_claim_text", models.TextField()),
                ("extraction_confidence", models.FloatField()),
                ("schema_valid", models.BooleanField(default=True)),
                ("extraction_version", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="cases.reviewcase",
                    ),
                ),
                (
                    "source_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="artifacts.documentsection",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["case", "claim_type"], name="extraction__case_id_0c3297_idx"
                    )
                ],
            },
        ),
    ]
