# Generated by Django 5.2.12 on 2026-03-25 17:30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("event_type", models.CharField(max_length=64)),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("user", "User"),
                            ("reviewer", "Reviewer"),
                            ("job", "Job"),
                        ],
                        max_length=16,
                    ),
                ),
                ("actor_id", models.CharField(blank=True, max_length=64, null=True)),
                ("correlation_id", models.CharField(db_index=True, max_length=64)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_events",
                        to="cases.reviewcase",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["case", "created_at"], name="audits_audi_case_id_7d9c27_idx"
                    )
                ],
            },
        ),
    ]
