# Generated by Django 5.2.12 on 2026-03-25 17:30

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("queue_name", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unassigned", "Unassigned"),
                            ("assigned", "Assigned"),
                            ("in_review", "In review"),
                            ("overridden", "Overridden"),
                            ("approved", "Approved"),
                            ("escalated", "Escalated"),
                            ("closed", "Closed"),
                        ],
                        default="unassigned",
                        max_length=32,
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(
                        choices=[
                            ("low_confidence", "Low confidence"),
                            ("schema_failure", "Schema failure"),
                            ("contradiction", "Contradiction"),
                            ("missing_support", "Missing support"),
                            ("manual_sampling", "Manual sampling"),
                            ("model_unavailable", "Model unavailable"),
                        ],
                        max_length=32,
                    ),
                ),
                ("sla_due_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_task",
                        to="cases.reviewcase",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewerAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("override", "Override"),
                            ("escalate", "Escalate"),
                            ("request_more_evidence", "Request more evidence"),
                            ("mark_false_positive", "Mark false positive"),
                            ("close", "Close"),
                        ],
                        max_length=32,
                    ),
                ),
                ("old_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                ("comment", models.TextField()),
                ("override_reason_code", models.CharField(blank=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviewer_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="reviews.reviewtask",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="reviewtask",
            index=models.Index(
                fields=["status", "queue_name", "sla_due_at"], name="reviews_rev_status_85429d_idx"
            ),
        ),
    ]
