# Generated by Django 5.2.12 on 2026-03-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revieweraction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("assign", "Assign"),
                    ("approve", "Approve"),
                    ("override", "Override"),
                    ("escalate", "Escalate"),
                    ("request_more_evidence", "Request more evidence"),
                    ("mark_false_positive", "Mark false positive"),
                    ("close", "Close"),
                ],
                max_length=32,
            ),
        ),
    ]
